services:

  web:
    build:
      context: ./django
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: web
    image: yarokrilka/microservice-project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data: