image:
  repository: 658301803468.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

replicaCount: 6

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: myapp-db-cluster.cluster-cpoi0am4exxf.eu-central-1.rds.amazonaws.com
  POSTGRES_USER: postgres
  POSTGRES_DB: myapp
  POSTGRES_PASSWORD: admin123AWS23
